### ISSUE TITLE
Sign out problem - Android

### ISSUE THREAD

**Issue by kroikie** [firebase/friendlychat-android#14]
_From @haivp3010 on September 11, 2016 3:3_

When signing out, it is still possible to press back to go back to the message screen. Is this the correct way the app works? Or should we put a finish() when pressing the sign out option menu?

_Copied from original issue: firebase/friendlychat-web#85_

**Comment by devvapp** [comment]
What was the resolution on this issue? I still have this issue

**Comment by kroikie** [comment]
Indeed we should call finish(); Thanks @haivp3010. This will be fixed when we next publish.
