### ISSUE TITLE
Sign in problem in android device On step 6

### ISSUE THREAD

**Issue by kroikie** [firebase/friendlychat-android#2]
_From @sohitvermamca on June 16, 2017 6:40_

Google sign-in failed in SignInActivity.java onActivityResult method when the GoogleSignInResult getting back it is not successful. Please solve this issue. 

_Copied from original issue: firebase/friendlychat-web#226_

**Comment by kroikie** [comment]
_From @arfirman1402 on July 7, 2017 1:45_

I still have same problem here. Whatever I running from android project or android-start project still have same problem. Please help us. Thank you Firebase.

**Comment by kroikie** [comment]
@sohitvermamca Could you include the error message that you are getting when sign in fails?

Also to be sure have you added your sha1 to your Firebase project?

**Comment by kroikie** [comment]
@sohivermamca seems like this is no longer an issue, I'll close for now please re-open if necessary.

**Comment by aplaceformyhead** [comment]
Slightly same problem on mine. 

> com.google.firebase.codelab.friendlychat E/SignInActivity: com.google.android.gms.auth.api.signin.GoogleSignInResult@e510846
> com.google.firebase.codelab.friendlychat E/SignInActivity: Google Sign-In failed.

getting this error and no more. I am sure that i am giving right account info to the app but can not sign-in.
Also added my sha-1 to firebase project.

**Comment by aplaceformyhead** [comment]
> Slightly same problem on mine.
> 
> > com.google.firebase.codelab.friendlychat E/SignInActivity: com.google.android.gms.auth.api.signin.GoogleSignInResult@e510846
> > com.google.firebase.codelab.friendlychat E/SignInActivity: Google Sign-In failed.
> 
> getting this error and no more. I am sure that i am giving right account info to the app but can not sign-in.
> Also added my sha-1 to firebase project.
> 
> @kroikie any suggest?

deleting and re-adding google-services.json has solved my problem.

**Comment by samtstern** [comment]
@aplaceformyhead there was a recent issue where `google-services.json` files were being generated by the backend without the `default_web_client_id` value which is used for Google Sign in.  I suspect that's what you ran into.  As you noticed, it's fixed now!

**Comment by radium0090** [comment]
`2019-07-31 17:30:28.404 31882-31882/com.google.firebase.codelab.friendlychat E/SignInActivity: Google Sign-In failed.`

Still get this problem.
does anyone still has same problem?
Any suggest ?

**Comment by mdsadiqueinam** [comment]
`2021-11-17 19:06:18.869 4929-4929/com.google.firebase.codelab.friendlychat W/SignInActivity: Sign in error
    com.firebase.ui.auth.FirebaseUiException: Exception serialization error, forced wrapping. Original: com.firebase.ui.auth.FirebaseUiException: Play Services update cancelled, original cause: com.google.android.gms.common.api.ApiException: 9: Error connecting to Google Play services
        at com.firebase.ui.auth.KickoffActivity.lambda$onCreate$1$KickoffActivity(KickoffActivity.java:71)
        at com.firebase.ui.auth.KickoffActivity$$ExternalSyntheticLambda0.onFailure(Unknown Source:2)
        at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

Still getting the same issue
