### ISSUE TITLE
Placeholder image does not show up

### ISSUE THREAD

**Issue by samiujan** [firebase/friendlychat-android#20]
In "Send Messages" - https://codelabs.developers.google.com/codelabs/firebase-android/#7 - it says "The new message should be visible first with a placeholder image then once the image upload is complete the selected image"

However, I don't see a placeholder image

I checked out master branch 1 hr ago from now

**Comment by kroikie** [comment]
@samiujan 
The placeholder feature is available however not implemented in the codelab. I will update the prose to reflect that we only display the message once the upload is complete. Thanks for the issue.
