### ISSUE TITLE
Step 10's MyFirebaseMessagingService.java doesn't actually display any notification

### ISSUE THREAD

**Issue by diarmaidlindsay** [firebase/friendlychat-android#21]
As the title says, onMessageReceived() is just Logging, and not displaying any notification.
Even the "ready baked" sample project is doing the same, no notification.

`     
Log.d(TAG, "FCM Message Id: " + remoteMessage.getMessageId());
Log.d(TAG, "FCM Notification Message: " +
               remoteMessage.getNotification());
Log.d(TAG, "FCM Data Message: " + remoteMessage.getData());
  `

**Comment by kroikie** [comment]
Hi @diarmaidlindsay, indeed the onMessageReceived callback only logs the incoming message. The codelab expects a notification message (aka display message). When the app is in the background notification messages are displayed by default so no need to generate a display notification. When the app is in the foreground the notification message is passed to onMessage callback but at that point the user is already using the app so no need to show a notification to get them to re-engage with the app so we just log it.

In a different app you may want to generate a notification message in the onMessage callback but for the purposes of the codelab it is not necessary.
