### ISSUE TITLE
no xml filess

### ISSUE THREAD

**Issue by oneilbogle1** [firebase/friendlychat-android#22]
after cloning the project says that it does not use a grande system then suggest i migrate this project but I'm not sure can someone help

**Comment by samtstern** [comment]
@oneilbogle1 make sure you clone the project and then open either the `android` or `android-start` folders in Android Studio, not the entire `friendlychat-android` folder.

**Comment by kroikie** [comment]
I think @samtstern is correct here, so closing please reopen if necessary.
