### ISSUE TITLE
9. Add Messages to the On-device Index

### ISSUE THREAD

**Issue by juanmanuelrq** [firebase/friendlychat-android#23]
My google search app not found information in my apps tap, 

I am using compile 'com.google.firebase:firebase-appindexing:10.2.1' like the example

and too, I am trying to update with this link https://firebase.google.com/docs/app-indexing/android/migrate that using compile 'com.google.firebase:firebase-appindexing:10.2.6'

but I not found the next function in the codelab example https://codelabs.developers.google.com/codelabs/firebase-android/#8

      //Before
      public Action getAction() {
       Thing object = new Thing.Builder()
        .setName(mText)
        .setUrl(mUrl)
        .build();

      return new Action.Builder(Action.TYPE_VIEW)
        .setObject(object)
        .build();
     }
      

      // After
     public Action getAction() {
         return Actions.newView(mText, mUrl);
     }

best regards

**Comment by kroikie** [comment]
Hi @juanmanuelrq the codelab assumes that you are using 10.0.0 or later. The before an after example you see is only for moving from pre 10.0.0 to current versions.
