### ISSUE TITLE
Typo in class name in tutorial

### ISSUE THREAD

**Issue by nathanfletcher** [firebase/friendlychat-android#24]
On the [10th step](https://codelabs.developers.google.com/codelabs/firebase-android/index.html?index=..%2F..%2Findex#9) in the **Firebase Android Codelab**, the heading of the code snippet to update the `MyFirebaseInstanceIdService` class says `MyInstanceIDListenerService.java` instead of `MyFirebaseInstanceIdService .java`

The name of the file in the repo is `MyFirebaseInstanceIdService .java` so seeing `MyInstanceIDListenerService.java` in the heading throws you off just a bit.

<img width="1263" alt="screen shot 2017-08-31 at 12 20 05 am" src="https://user-images.githubusercontent.com/1917416/29900733-31c04866-8de3-11e7-8005-e29dfc780b08.png">

**Comment by kroikie** [comment]
Thanks @nathanfletcher this should be fixed when the codelab is next published.
