### ISSUE TITLE
Deprecated code 

### ISSUE THREAD

**Issue by nukatron** [firebase/friendlychat-android#26]
Hi,

I've just come back to get over the tutorial again and I found that the way that create `FirebaseRecyclerAdapter` has been changed in `firebase-ui-database:3.0.0`. 

another thing is `AppInvite` is deprecated and when I tried to follow the tutorial I don't understand that why do we need to add `AppInvite.API` to `GoogleApiClient.Builder` because I didn't see that we use `GoogleApiClient` to invite friends (Do I miss understand?).

That all what I recognize. please apologize me if I miss understand. 

-Thank

**Comment by samtstern** [comment]
@nukatron thanks for the heads up!

**Comment by samtstern** [comment]
@nukatron I sent this PR to update everything:
https://github.com/firebase/friendlychat-android/pull/27

You can look there for how the codleab will change to deal with the new version of FirebaseUI.  And you're right, we don't need `AppInvite.API` on the `GoogleApiClient`.  Good catch!

**Comment by kroikie** [comment]
Updated the codelab with new FirebaseUI usage and removed the `AppInvite.API` from the `GoogleApiClient`. Thanks @nukatron.
