### ISSUE TITLE
My message list isn't display at android screen

### ISSUE THREAD

**Issue by Abealkindy** [firebase/friendlychat-android#29]
why my message list cant displayed, even i was copied all of code from this repo to my project?
*sorry for my bad english

**Comment by stupidly-logical** [comment]
@Abealkindy There are 2 apps in this repo. One is "android-start", the other one is "android".
android-start is the bare-bone structure of the final app whereas android is the complete app. I suggest you go through this example https://codelabs.developers.google.com/codelabs/firebase-android/#0
