### ISSUE TITLE
populateViewHolder(...) - is this method deprecated?

### ISSUE THREAD

**Issue by johnnyoncode** [firebase/friendlychat-android#31]
https://firebaseui.com/docs/android/com/firebase/ui/FirebaseRecyclerViewAdapter.html
```
public void populateViewHolder(ChatMessageViewHolder chatMessageViewHolder, ChatMessage chatMessage)
```
it appears in here too : https://codelabs.developers.google.com/codelabs/firebase-android/?authuser=0#8

`@Override
protected void populateViewHolder(final MessageViewHolder viewHolder, FriendlyMessage friendlyMessage, int position)`

**Comment by samtstern** [comment]
@johnnyoncode a few things:

   1. firebaseui.com is no longer in use, if you found a link to that somewhere please let me know and I will remove it.
   2. That definitely is a bug, assigning to @kroikie to fix it.

**Comment by kroikie** [comment]
Thanks for catching that @johnnyoncode. Fixed.
