### ISSUE TITLE
sent picture does't show up in chat

### ISSUE THREAD

**Issue by leonidas79** [firebase/friendlychat-android#40]
Hello
After completing step 8  i could select a picture to send , but then i have a big spinner picture loading instead of the pic that i sent.

**Comment by samtstern** [comment]
Thanks @madmax330  for jumping in to help.

@leonidas79 did you ever get it working?

**Comment by leonidas79** [comment]
i tried upload other pictures and it's working , i tested it in emulator , not yet in real device.

**Comment by samtstern** [comment]
Ok great, I think we can close this but @leonidas79 if you have any troubles on the real device just ping this thread and we can re-open it.

**Comment by bighwstyle** [comment]
Is it closed? Image uploading is working. I can see it in the firebase console. But I can't see the pic after showing placeholder image.

**Comment by marwazihs** [comment]
@bighwstyle image not showing could be related to the `.getDownloadUrl()` that has been deprecated. Hence, the friendlyMessage.imageUrl stores the wrong URL.

I solved it by using the following code to replace the `putImageInStorage` function:

```
private void putImageInStorage(final StorageReference storageReference, Uri uri, final String key) {

        UploadTask uploadTask = storageReference.putFile(uri);

        Task<Uri> urlTask = uploadTask.continueWithTask(new Continuation<UploadTask.TaskSnapshot, Task<Uri>>() {
            @Override
            public Task<Uri> then(@NonNull Task<UploadTask.TaskSnapshot> task) throws Exception {
                if (!task.isSuccessful()) {
                    throw task.getException();
                }

                return storageReference.getDownloadUrl();
            }
        }).addOnCompleteListener(new OnCompleteListener<Uri>() {
            @Override
            public void onComplete(@NonNull Task<Uri> task) {
                if (task.isSuccessful()) {

                    String downloadUrl = task.getResult().toString();

                    FriendlyMessage friendlyMessage = new FriendlyMessage(null, mUsername, mPhotoUrl,downloadUrl);

                    mFirebaseDatabaseReference.child(MESSAGES_CHILD).child(key).setValue(friendlyMessage);

                } else {
                    Log.w(TAG, "Image upload task was not successful.",
                            task.getException());
                }
            }
        });
```

**Comment by HALLneufmilles** [comment]
hello,
If you have this problem, maybe is due to the rule:
`rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}`
