### ISSUE TITLE
Get Download Url Method Error

### ISSUE THREAD

**Issue by sumitchawandia** [firebase/friendlychat-android#51]
getDownloadUrl()  Method Show the error

**Comment by ankode** [comment]
@morganchen12 
In method _putImageInStorage_ of _MainActivity_ 
```java
    @Override
               public void onComplete(@NonNull Task<UploadTask.TaskSnapshot> task) {
                   if (task.isSuccessful()) {
                       FriendlyMessage friendlyMessage =
                               new FriendlyMessage(null, mUsername, mPhotoUrl,
                                       task.getResult().getMetadata().getDownloadUrl()
                                               .toString());
                       mFirebaseDatabaseReference.child(MESSAGES_CHILD).child(key)
                               .setValue(friendlyMessage);
                   } else {
                       Log.w(TAG, "Image upload task was not successful.",
                               task.getException());
                   }
               }
```
**getDownloadUrl()** of `task.getResult().getMetadata().getDownloadUrl()` is giving error **"cannot resolve method 'getDownloadUrl()' "**

**Comment by ankode** [comment]
> **Fixed**

replace `task.getResult().getMetadata().getDownloadUrl() ` by `task.getResult().getStorage()().getDownloadUrl() `

Reason is mentioned on [StackOverflow](https://stackoverflow.com/questions/50158921/firebase-storage-retrieves-a-long-lived-download-url-using-getdownloadurl-no):
_The getDownloadUrl() and getDownloadUrls() methods of the StorageMetadata class are now deprecated. Use getDownloadUrl() from StorageReference instead._

**Comment by sumitchawandia** [comment]
Thanks @ankode it's worked.

**Comment by kevinkoech** [comment]
I faced the same problem but I got the answer

Just add `.getStorage()`  infront of `.getDownloadurl`

to be like this below

    .getStorage().getDownloadUrl 

LEAVE EVERYTHING IN THAT LINE DONT ALTER JUST ADD `.getStorage()`

**Comment by YannickNascimento** [comment]
you can find the solution here: https://stackoverflow.com/a/51076403/3135287

**Comment by luongchung** [comment]
> > **Fixed**
> 
> replace `task.getResult().getMetadata().getDownloadUrl() ` by `task.getResult().getStorage()().getDownloadUrl() `
> 
> Reason is mentioned on [StackOverflow](https://stackoverflow.com/questions/50158921/firebase-storage-retrieves-a-long-lived-download-url-using-getdownloadurl-no):
> _The getDownloadUrl() and getDownloadUrls() methods of the StorageMetadata class are now deprecated. Use getDownloadUrl() from StorageReference instead._

Thanks Bro !

**Comment by kevinkoech** [comment]
I had tried to help people on stackoverflow to answer this but they raised my reputation higher so I cant answer there...too bad

**Comment by dankhalif** [comment]
> I faced the same problem but I got the answer
> 
> Just add `.getStorage()` infront of `.getDownloadurl`
> 
> to be like this below
> 
> ```
> .getStorage().getDownloadUrl 
> ```
> 
> LEAVE EVERYTHING IN THAT LINE DONT ALTER JUST ADD `.getStorage()`

this code saved me thank you so much

**Comment by mohannmpl** [comment]
Just replace from taskSnapshot.getDownloadUrl().toString() to  mImageUri.toString() it works thanks

**Comment by Sachayanthan-V** [comment]
I want 
task.getResult().getDownloadUrl().toString() -----> this statement

task.getResult().getStorage().getDownloadUrl().toString() -----> this is works and doesn't shows any error but in app I try to open its crashes.

So, What can I do friends.?

**Comment by abdou333** [comment]
i have a problem , after a long search i din't a suitable solution 
ca not resolve getdonwloadUrl()
please help me 
.addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
@override
public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
// Upload succeeded
Log.d(TAG, "OnSuccessListener");

                    Uri downloadUri = taskSnapshot.getMetadata().getDownloadUrl();
                    Log.d(TAG, "downloadUri: " + downloadUri);

                    pdfsize = taskSnapshot.getMetadata().getSizeBytes();
                    pdfsize = pdfsize/1048576;
                    Log.d(TAG, "onSuccess: fileSize"+pdfsize);


                    uploaddate = FindCurrentDate();




                    Toast.makeText(MyUploadService.this, getString(R.string.upload_success), Toast.LENGTH_LONG).show();

                    uploadOnDB(downloadUri.toString(), pdfref.getName());

                    broadcastUploadFinished(downloadUri, fileUri);
                    showUploadFinishedNotification(pdfname, downloadUri, fileUri);
                    taskCompleted();

                }
            })

**Comment by coder63480** [comment]
my code isn´t working can you help me?

here is my code:

private void saveToStories() {

        final DatabaseReference userStoryDb = FirebaseDatabase.getInstance().getReference().child("users").child(Uid).child("story");
        final String key = userStoryDb.push().getKey();

        StorageReference filePath = FirebaseStorage.getInstance().getReference().child("captures").child(key);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        rotateBitmap.compress(Bitmap.CompressFormat.JPEG, 20, baos);
        byte[] dataToUpload = baos.toByteArray();
        UploadTask uploadTask = filePath.putBytes(dataToUpload);

        uploadTask.addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
            @Override
            public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                Uri imageUrl = taskSnapshot.getDownloadUrl();

                Long currentTimestamp = System.currentTimeMillis();
                Long endTimestamp = currentTimestamp + (24*60*60*1000);

                Map<String, Object> mapToUpload = new HashMap<>();
                mapToUpload.put("imageUrl", imageUrl.toString());
                mapToUpload.put("timestampBeg", currentTimestamp);
                mapToUpload.put("timestampEnd", endTimestamp);

                userStoryDb.child(key).setValue(mapToUpload);

                finish();
                return;
            }
        });

        uploadTask.addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                finish();
                return;
            }
        });
    }

**Comment by burhanuddinhamzabhai** [comment]
> > I faced the same problem but I got the answer
> > Just add `.getStorage()` infront of `.getDownloadurl`
> > to be like this below
> > ```
> > .getStorage().getDownloadUrl 
> > ```
> > 
> > 
> > LEAVE EVERYTHING IN THAT LINE DONT ALTER JUST ADD `.getStorage()`
> 
> this code saved me thank you so much

it is not giving valid URL for me

**Comment by sonali822** [comment]
val downloadUrl = taskSnapshot.downloadUrl
this taskSnapshot.downloadUrl shows me error please anyone can help??
my image is not saved in firebase only this error in my code please help

**Comment by burhanuddinhamzabhai** [comment]
i did this instead and it resolved the problem for me
**Task<Uri> task = taskSnapshot.getMetadata().getReference().getDownloadUrl();
 task.addOnSuccessListener(new OnSuccessListener<Uri>() {
                            @Override
                            public void onSuccess(Uri uri) {
                                  String url = uri.toString();
                               }**

**Comment by rajathbagre** [comment]
taskSnapshot.getMetadata().getReference().getDownloadUrl().toString() use this it worked for me

**Comment by Azimeraw** [comment]
taskSnapshot.getMetadata().getReference().getDownloadUrl().toString() and also use taskSnapshot.getStorage().getDownloadUrl().toString()  this it is not  worked for me could you help me

**Comment by burhanuddinhamzabhai** [comment]
> taskSnapshot.getMetadata().getReference().getDownloadUrl().toString() and also use taskSnapshot.getStorage().getDownloadUrl().toString() this it is not worked for me could you help me

Task task = taskSnapshot.getMetadata().getReference().getDownloadUrl();
task.addOnSuccessListener(new OnSuccessListener() {
@override
public void onSuccess(Uri uri) {
String url = uri.toString();
}
try this

**Comment by hetdesaii** [comment]
This work very well and easy way to write code for uploading and downloading image file.


```java
final StorageReference photoRef = mChatStorageReference.child(selectedImageUri.getLastPathSegment());
            photoRef.putFile(selectedImageUri).addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
                @Override
                public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                    Toast.makeText(MainActivity.this, "Image Successfully uploaded", Toast.LENGTH_SHORT).show();
                    photoRef.getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
                        @Override
                        public void onSuccess(Uri uri) {
                            FriendlyMessage friendlyMessage = new FriendlyMessage(null, mUsername, uri.toString());
                            mMessagesDatabaseReference.push().setValue(friendlyMessage);
                        }
                    });
                }
            }).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {
                    Toast.makeText(MainActivity.this, "Image Fail to upload", Toast.LENGTH_SHORT).show();
                }
            });
```

**Comment by Azimeraw** [comment]
Thanks a lot
