### ISSUE TITLE
Step 4: Sync your project with gradle files error

### ISSUE THREAD

**Issue by SokimMan** [firebase/friendlychat-android#52]
Line 36: implementation 'com.android.support:design:27.1.1' in the build.gradle file is giving an error when I try to sync the project with gradle files saying that I am trying to mix versions  27.1.1 and 26.1.0

**Comment by bighwstyle** [comment]
I have same issue as well. I can't find 26.1.0.

**Comment by samtstern** [comment]
Thanks @bighwstyle
