### ISSUE TITLE
Step 4: Gradle project sync failed, Failed to resolve: viewmodel and Failed to resolve: runtime

### ISSUE THREAD

**Issue by bighwstyle** [firebase/friendlychat-android#53]
I'd got those fail messages during sync.
![image](https://user-images.githubusercontent.com/29017575/41454845-ee9e5c24-70b5-11e8-9a8f-0a8d180a448c.png)

When you face this issue. You meed to change the repository order of repositories in Project level build:gradle

`buildscript {
    repositories {
        google()
        jcenter()
        mavenLocal()
        maven { url 'https://maven.fabric.io/public'  }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'io.fabric.tools:gradle:1.24.4'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenLocal()
    }
}`

Reference: https://stackoverflow.com/a/50563942/8050752

**Comment by misolab** [comment]
감사합니다.
