### ISSUE TITLE
Extra curly brace needs to be removed in sample code

### ISSUE THREAD

**Issue by arun-anbumani** [firebase/friendlychat-android#58]
![capture](https://user-images.githubusercontent.com/6822497/46820662-ff07bc00-cd43-11e8-97cc-0b637d0b3b04.PNG)

section 9:

```
@Override
protected void onBindViewHolder(final MessageViewHolder viewHolder, FriendlyMessage friendlyMessage, int position) {

...
if (friendlyMessage.getText() != null) {
    // write this message to the on-device index
    FirebaseAppIndex.getInstance()
            .update(getMessageIndexable(friendlyMessage));
} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> needs to be removed. 

// log a view action on it
FirebaseUserActions.getInstance().end(getMessageViewAction(friendlyMessage));
}
```

**Comment by samtstern** [comment]
@arun-anbumani I believe that bracket is correct.  It goes with the `if` statement and the other statement should be on the outside.  See the solution below:
https://github.com/firebase/friendlychat-android/blob/master/android/app/src/main/java/com/google/firebase/codelab/friendlychat/MainActivity.java#L241-248
