### ISSUE TITLE
Failed to resolve two packages while trying to gradle sync.

### ISSUE THREAD

**Issue by n3at-fr33k** [firebase/friendlychat-android#59]
Following the Codelab and such, and can't get past the very first steps, of running the test app to see nothing happening. The build won't finish, because I get the following errors:
`Failed to resolve: play-services-basement`

`Failed to resolve: play-services-measurement-base`

The steps I did before this included:
1. Opening the project, and following this prompt:
`Unregistered VCS root detected
					The directory C:\Users\bcook\friendlychat-android is under Git, but is not registered in the Settings.
					Add root  Configure  Ignore`
I clicked `Add root`. Then, it re-ran the Gradle Build, and then failed.

`Stats:
Browser: Google Chrome
Browser version: 69.0.3497.100 (Official Build) (64-bit)
Operating system: Windows 10
Operating system version: 1803`

**Comment by samtstern** [comment]
This should be fixed by some recent updates.  Sorry for the (incredibly) slow response here!
