### ISSUE TITLE
Error on step 4 with android-start: Sync your project with gradle files

### ISSUE THREAD

**Issue by alturionEw** [firebase/friendlychat-android#61]
Running project android-start in Android Stdio 3.2.1 gives this error error:
Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

while grow-android-start project works perfectly, why?

**Comment by samtstern** [comment]
I made a number of updates today that should fix this (I know you filed it forever ago, but thought I'd mention it).
