### ISSUE TITLE
Run icon not enabled

### ISSUE THREAD

**Issue by Lokeshvellore** [firebase/friendlychat-android#67]
after downloading and configuring json ,after syncing the run icon or option is not displayed and i'm using usb debugging 
![capture](https://user-images.githubusercontent.com/45627086/50726216-eedb5f00-112f-11e9-8948-c494e3c79814.PNG)

**Comment by samtstern** [comment]
That seems like it is because the sync has failed, which we can talk about in #68.  Please see the questions I asked there.

**Comment by Lokeshvellore** [comment]
Thanks sir, I resolved problem and the app is working great for me, but
even after sending invites, they are not getting any invite messages, what
should I do ?

**Comment by samtstern** [comment]
@Lokeshvellore without more technical information it's not possible to answer that question.  I'd suggest asking on the firebase-talk mailing list with more info.
