### ISSUE TITLE
gradle project sync failed 

### ISSUE THREAD

**Issue by Lokeshvellore** [firebase/friendlychat-android#68]

**Comment by samtstern** [comment]
@Lokeshvellore we need a lot more information than this to help you with this issue!  As it stands there is nothing I can do, so I will close it.  However if you can provide the following, I am happy to re-open it:

- Steps to reproduce the issue
- Information about your environment (are you using Android Studio?  If so, what version?)
- Logs from the failed gradle sync.  What is the step that is failing?  What is the error?
