### ISSUE TITLE
Image sending in android-starter

### ISSUE THREAD

**Issue by kroikie** [firebase/friendlychat-android#7]
_From @salimshivani on March 2, 2017 12:47_

There is an issue in android-starter in sending an image. When the image is sent, either the app crashes or the app image is not sent. Just the user image along with the name is displayed.

Also, when the text message is sent, the user image is not displayed.

_Copied from original issue: firebase/friendlychat-web#164_

**Comment by kroikie** [comment]
Hi @salimshivani I'm unable to reproduce this, is this still an issue?

**Comment by kroikie** [comment]
_From @salimshivani on April 3, 2017 1:28_

Thank you for the response, but then can internet connectivity be the reason for crashing the app?

Since, in initial stage, the app was just not displaying the imageview for the image sent, but later on, it started crashing.

**Comment by kroikie** [comment]
Could you provide the stack trace of the crash?

**Comment by kroikie** [comment]
@salimshivani

**Comment by salimshivani** [comment]
@kroikie I had left it after I didn't understood the working of Firebase at that time. And I am sorry for that.

**Comment by kroikie** [comment]
@salimshivani glad you got things working, closing.
