### ISSUE TITLE
.getDownloadUrl() error I faced.

### ISSUE THREAD

**Issue by VishwarajsinhRaol** [firebase/friendlychat-android#71]
public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                            Handler handler = new Handler();
                            handler.postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    mProgressBar.setProgress(0);
                                }
                            }, 5000);

                            Toast.makeText(MainActivity.this, "Upload successful", Toast.LENGTH_LONG).show();
                            Upload upload = new Upload(mEditTextFileName.getText().toString().trim(),
                                    taskSnapshot.getDownloadUrl().toString());
                            String uploadId = mDatabaseRef.push().getKey();
                            mDatabaseRef.child(uploadId).setValue(upload);
                        }
                    })
                    .addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            Toast.makeText(MainActivity.this, e.getMessage(), Toast.LENGTH_SHORT).show();
                        }
                    })

**Comment by puf** [comment]
On newer SDK versions, the `getDownloadUrl` method requires another round trip to the server and is no longer available on `TaskSnapshot`. You instead need call `getDownloadUrl()` on the reference, and wait for the task to complete. Check the latest documentation for an example of [getting the download URL](https://firebase.google.com/docs/storage/android/download-files#download_data_via_url), and [getting the download URL right after uploading a file](https://firebase.google.com/docs/storage/android/upload-files#get_a_download_url).
