### ISSUE TITLE
Firebase android codelab step 6 admob crash

### ISSUE THREAD

**Issue by aplaceformyhead** [firebase/friendlychat-android#72]
When doing step 6, i got that error 

> com.google.firebase.codelab.friendlychat E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.google.firebase.codelab.friendlychat, PID: 27905
>     java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

then a message telling google mobile ads sdk was initialized incorrectly.

is there way to continue this tutorial without admob? or may be just suppressing admob ?

**Comment by yhdesai** [comment]
If you have correctly already added the dependency, You need to add the value which you can do by following this
https://stackoverflow.com/questions/53294162/cannot-import-com-google-android-gmsplay-services-ads17-1-1/53443104#53443104

**Comment by aplaceformyhead** [comment]
I deleted my current project and re-do all steps to 6 of the tutorial, i just removed  admob imports and crashing problem has gone! closing this issue, thanks.
