### ISSUE TITLE
Step 5: No android.keystore + misspelling [SOLVED]. Update codelab?

### ISSUE THREAD

**Issue by siliconmoo** [firebase/friendlychat-android#78]
In Step 5, the statement ```Keytool -alias androiddebugkey -keystore ~/.android/debug.keystore -list -v -storepass android``` fails for the following reasons.

1. ```Keytool``` should read ```keytool```
2. No android.keystore.  Having just installed Android Studio, my android.key didn't exist, so this step failed. The following helped:  ```keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US"```

**Comment by kroikie** [comment]
@siliconmoo thanks for calling that out. I'll update the prose.

**Comment by samtstern** [comment]
@siliconmoo thanks!  I updated the `keytool` line and also added this statement:
"If this file does not exist, Android Studio will create it for you the first time you run any app."

IMO that's the easiest way to create the debug keystore for most people, and the least likely to break for us in the future.
