### ISSUE TITLE
why cloud firestore isn't used to replace realtime database?

### ISSUE THREAD

**Issue by tempral** [firebase/friendlychat-android#85]
[differences](https://firebase.google.com/docs/database/rtdb-vs-firestore)

do you think that is generally always better to use Cloud Firestore?

**Comment by samtstern** [comment]
@tempral we do think that Cloud Firestore is better for most new apps but there's no need to replace RTDB with Cloud Firestore in existing codebases like this one!  RTDB is a great product and will continue to be fully supported.
